#!/usr/bin/env bash
#
# BANKONGSETON — Oracle Cloud ARM first-time installer.
# Run ONCE on the VM:  sudo bash install.sh
#
# What it does:
#   - installs nginx, certbot, git, uv, build tools
#   - creates system user 'banko'
#   - clones the repo to /opt/bankongseton
#   - builds a venv and installs python deps
#   - generates JWT_SECRET / FLASK_SECRET_KEY
#   - writes the env file
#   - installs systemd units + nginx site
#   - opens the firewall (ufw) and optionally runs certbot
#
# Safe to re-run: idempotent for the most part, but it will NOT overwrite an
# existing /opt/bankongseton/.env (so re-runs keep your secrets).
set -euo pipefail

# ── Config (edit or pass via env) ─────────────────────────────────────────────
REPO_URL="${REPO_URL:-git@github.com:Rumijul/BANKONGSETON.git}"
APP_DIR="${APP_DIR:-/opt/bankongseton}"
DEPLOY_DIR="$APP_DIR/deploy/oracle"
USER_NAME="banko"
DOMAIN="${DOMAIN:-}"          # e.g. banko.example.edu — leave empty for HTTP-on-IP
ADMIN_EMAIL="${ADMIN_EMAIL:-}"
PYTHON_BIN="$(command -v python3)"

echo "==> BANKONGSETON Oracle installer"
echo "    REPO_URL = $REPO_URL"
echo "    APP_DIR  = $APP_DIR"
echo "    DOMAIN   = ${DOMAIN:-<none — HTTP on public IP>}"

# ── Detect package manager ───────────────────────────────────────────────────
if   command -v apt-get >/dev/null 2>&1; then PM="apt";
elif command -v dnf     >/dev/null 2>&1; then PM="dnf";
elif command -v yum     >/dev/null 2>&1; then PM="yum";
else echo "Unsupported package manager"; exit 1; fi

# ── OS packages ───────────────────────────────────────────────────────────────
echo "==> Installing OS packages ($PM)"
if [ "$PM" = "apt" ]; then
  sudo apt-get update -y
  sudo apt-get install -y nginx certbot python3-certbot-nginx git curl \
    python3-venv python3-dev build-essential libpq-dev ufw
elif [ "$PM" = "dnf" ] || [ "$PM" = "yum" ]; then
  sudo "$PM" install -y nginx certbot python3-certbot-nginx git curl \
    python3-virtualenv gcc python3-devel libpq-devel ufw
fi

# ── system user ───────────────────────────────────────────────────────────────
if ! id "$USER_NAME" >/dev/null 2>&1; then
  echo "==> Creating user $USER_NAME"
  sudo useradd --system --home-dir "$APP_DIR" --shell /usr/sbin/nologin "$USER_NAME" || \
  sudo useradd --system -d "$APP_DIR" -s /usr/sbin/nologin "$USER_NAME"
fi

# ── clone / update repo ───────────────────────────────────────────────────────
if [ ! -d "$APP_DIR/.git" ]; then
  echo "==> Cloning repo"
  sudo mkdir -p "$APP_DIR"
  sudo chown -R "$USER_NAME":"$USER_NAME" "$APP_DIR"
  sudo -u "$USER_NAME" git clone "$REPO_URL" "$APP_DIR"
else
  echo "==> Repo exists — pulling"
  sudo -u "$USER_NAME" git -C "$APP_DIR" pull --ff-only || true
fi

# ── python venv ───────────────────────────────────────────────────────────────
echo "==> Creating venv + installing deps"
sudo -u "$USER_NAME" "$PYTHON_BIN" -m venv "$APP_DIR/venv"
# shellcheck disable=SC1091
sudo -u "$USER_NAME" bash -c "
  source '$APP_DIR/venv/bin/activate'
  pip install --upgrade pip wheel
  pip install -r '$APP_DIR/backend/api/requirements_api.txt'
  pip install -r '$APP_DIR/backend/dashboard/requirements.txt'
  pip install -r '$DEPLOY_DIR/requirements-deploy.txt'
"

# ── secrets / env file (keep existing) ────────────────────────────────────────
if [ ! -f "$APP_DIR/.env" ]; then
  echo "==> Generating .env"
  JWT_SECRET="$(sudo -u "$USER_NAME" "$APP_DIR/venv/bin/python" -c 'import secrets;print(secrets.token_urlsafe(48))')"
  FLASK_SECRET_KEY="$(sudo -u "$USER_NAME" "$APP_DIR/venv/bin/python" -c 'import secrets;print(secrets.token_urlsafe(32))')"
  FINANCE_PASSWORD="$(sudo -u "$USER_NAME" "$APP_DIR/venv/bin/python" -c 'import secrets;print(secrets.token_urlsafe(16))')"
  ADMIN_PASSWORD="$(sudo -u "$USER_NAME" "$APP_DIR/venv/bin/python" -c 'import secrets;print(secrets.token_urlsafe(16))')"
  CORS="http://localhost,http://127.0.0.1"
  [ -n "$DOMAIN" ] && CORS="$CORS,https://$DOMAIN"
  SERVER_URL="${DOMAIN:+https://$DOMAIN}"
  sudo -u "$USER_NAME" bash -c "cat > '$APP_DIR/.env' <<EOF
# BANKONGSETON production env (generated by install.sh)
FLASK_ENV=production
DEBUG_MODE=false
FLASK_SECRET_KEY=$FLASK_SECRET_KEY
JWT_SECRET=$JWT_SECRET
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$ADMIN_PASSWORD
FINANCE_USERNAME=finance
FINANCE_PASSWORD=$FINANCE_PASSWORD
# Supabase Postgres — real project ref (host is IPv6-only; use pooler below if VM has no IPv6 egress)
DATABASE_URL=postgresql://postgres:***@db.pmzaxwqygzuuiawdrkvv.supabase.co:5432/postgres
# IPv4 fallback (session pooler, ap-southeast-1) — swap in if direct :5432 won't connect:
# DATABASE_URL=postgresql://postgres:***@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
CORS_ORIGINS=$CORS
SERVER_URL=$SERVER_URL
WEB_CONCURRENCY=1
GUNICORN_WORKERS=1
EOF"
  sudo chmod 600 "$APP_DIR/.env"
  echo "    Admin login: admin / $ADMIN_PASSWORD   (change in .env)"
else
  echo "==> $APP_DIR/.env exists — keeping it"
fi

# ── systemd units ─────────────────────────────────────────────────────────────
echo "==> Installing systemd units"
sudo cp "$DEPLOY_DIR/bankongseton-api.service" /etc/systemd/system/
sudo cp "$DEPLOY_DIR/bankongseton-web.service"  /etc/systemd/system/
sudo cp "$DEPLOY_DIR/bankongseton-kiosk.service" /etc/systemd/system/
sudo cp "$DEPLOY_DIR/bankongseton-tech.service"  /etc/systemd/system/
sudo sed -i "s#__APP_DIR__#$APP_DIR#g; s#__USER__#$USER_NAME#g" \
  /etc/systemd/system/bankongseton-api.service \
  /etc/systemd/system/bankongseton-web.service \
  /etc/systemd/system/bankongseton-kiosk.service \
  /etc/systemd/system/bankongseton-tech.service
sudo systemctl daemon-reload
sudo systemctl enable bankongseton-api bankongseton-web bankongseton-kiosk bankongseton-tech

# ── nginx ──────────────────────────────────────────────────────────────────────
echo "==> Installing nginx site"
sudo cp "$DEPLOY_DIR/nginx-bankongseton.conf" /etc/nginx/sites-available/bankongseton
if [ -n "$DOMAIN" ]; then
  sudo sed -i "s#__SERVER_NAME__#$DOMAIN#g" /etc/nginx/sites-available/bankongseton
else
  sudo sed -i "s#__SERVER_NAME__#_#g" /etc/nginx/sites-available/bankongseton
fi
sudo ln -sf /etc/nginx/sites-available/bankongseton /etc/nginx/sites-enabled/bankongseton
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl enable nginx
sudo systemctl restart nginx

# ── firewall ───────────────────────────────────────────────────────────────────
echo "==> Configuring firewall (ufw)"
sudo ufw --force enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo "    NOTE: also open 80/443/22 in the OCI VCN Security List (console)."

# ── start services ────────────────────────────────────────────────────────────
echo "==> Starting services"
sudo systemctl restart bankongseton-api bankongseton-web bankongseton-kiosk bankongseton-tech

# ── TLS (optional) ────────────────────────────────────────────────────────────
if [ -n "$DOMAIN" ] && [ -n "$ADMIN_EMAIL" ]; then
  echo "==> Requesting Let's Encrypt certificate"
  sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$ADMIN_EMAIL" --redirect
  sudo systemctl restart nginx
else
  echo "==> Skipping TLS (no DOMAIN/ADMIN_EMAIL). Site is HTTP on the public IP."
fi

echo
echo "==> DONE. Check status:"
echo "    sudo systemctl status bankongseton-api bankongseton-web nginx"
echo "    curl -k https://localhost/api/health"
